TRIGGER NODE API

diff --git a/.github/workflows/javaapi.yml b/.github/workflows/javaapi.yml
--- a/.github/workflows/javaapi.yml
+++ b/.github/workflows/javaapi.yml
@@ -30,8 +30,12 @@ env:
   ECR_REPOSITORY_NODEAPI: "nodeapi"
   ECR_REPOSITORY_NGINX: "nginx"
 
+  ECS_JAVA_TASK: "java-task"
+  ECS_CLUSTER: "ecs-task"
+  ECS_SERVICE: "java-task-service-xsh8ud3g"
+
 jobs:
-  build-angular:
+  build-javaapi:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -60,3 +64,57 @@ jobs:
           tags: |
             ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_JAVA }}:${{ github.run_number }}
             ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_JAVA }}:latest
+
+  deploy:
+    needs: build-javaapi
+    name: Deploy to ECS-javaapi task
+    runs-on: ubuntu-latest
+    steps:
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
+          aws-region: ${{ env.AWS_REGION }}
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Download task definition
+        run: |
+          aws ecs describe-task-definition \
+          --task-definition ${{ env.ECS_JAVA_TASK }} \
+          --query taskDefinition \
+          --region ${{ env.AWS_REGION }} > task-definition.json
+
+      - name: Get version from VERSION file
+        id: get-version
+        run: |
+          if [ -f VERSION ]; then
+            VERSION=$(cat VERSION)
+          else
+            echo "VERSION file not found. Exiting..."
+            exit 1
+          fi
+          echo "Current version: $VERSION"
+          echo version=$VERSION >> $GITHUB_OUTPUT
+
+      - name: Fill in the new image ID in the Amazon ECS task definition
+        id: task-def
+        uses: aws-actions/amazon-ecs-render-task-definition@v1
+        with:
+          task-definition: task-definition.json
+          container-name: ${{ env.ECR_REPOSITORY_JAVA }}
+          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_JAVA }}:${{ steps.get-version.outputs.version }}
+
+      - name: Deploy to ECS
+        id: deploy-ecs
+        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
+        with:
+          service: ${{ env.ECS_SERVICE }}
+          cluster: ${{ env.ECS_CLUSTER }}
+          task-definition: ${{ steps.task-def.outputs.task-definition }}
+          wait-for-service-stability: true
